# Generated by Django 5.2.14 on 2026-07-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.CharField(help_text='Comma-separated tech tags, e.g., Python, Django, Flask', max_length=200),
        ),
    ]
